/**
 * @file Patterns translations for Experience Site.
 */

import { patterns } from './patterns';
import { urls } from './urls';

const tokens = {
    USER_ENCONDED_TOKEN: 'dXNlcklk',
    CHANGE_PASS_ENCONDED_TOKEN: 'Y2hhbmdlUGFzc3dvcmQ',
    EMAIL_CHANGE_ENCONDED_TOKEN: 'ZW1haWxDaGFuZ2U'
};

const validations = {
    PASS_CONTAINS_EMAIL_OR_NAME_CHARS: 5,
    VAT_CHAR_LIMIT: 18,
    PERSONAL_FIRSTNAME_CHAR_LIMIT: 34,
    PERSONAL_LASTNAME_CHAR_LIMIT: 35,
    PRIVATEBILLING_FIRSTNAME_CHAR_LIMIT: 34,
    PRIVATEBILLING_LASTNAME_CHAR_LIMIT: 35,
    PRIVATEBILLING_ADDRESS_CHAR_LIMIT: 35,
    PRIVATEBILLING_POSTALCODE_CHAR_LIMIT: 10,
    PRIVATEBILLING_CITY_CHAR_LIMIT: 35,
    COMPANYBILLING_NAME_CHAR_LIMIT: 70,
    COMPANYBILLING_ADDRESS_CHAR_LIMIT: 35,
    COMPANYBILLING_CITY_CHAR_LIMIT: 35,
    COMPANYBILLING_POSTALCODE_CHAR_LIMIT: 10
};

export { patterns, urls, tokens, validations };