/**
 * @author Diogo Gonçalves
 * @description Class to parse the response from Barcode Generation Callout
 *
 * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer                Date            Description
 * ------------------------------------------------------------------------------------
 * Diogo Gonçalves          11/04/2024      ECOMM-105: Original version
 */
public class COMM_SL_BarcodeResponse {
    public String content;
    public String fileType;
    public String resultCode;
    public String resultDesc;
}