/**
 * @author Daniel Lascas
 * @description COMM_MonthlyFiscalDocumentControl__c repository
 *
 * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer        Date             Description
 * -----------------------------------------------------------------------------------
 * Daniel Lascas    15/04/2024       ECOMM-194: Original version
 **/
public inherited sharing class COMM_REP_MonthlyFiscalDocumentControl extends FW_SobjectRep implements COMM_IREP_MonthlyFiscalDocumentControl {
}