/**
 * @author           Daniel Reto
 * @description      Order Item Summary Domain object interface
 *
 * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer        Date             Description
 * -----------------------------------------------------------------------------------
 * Daniel Reto      28/06/2024       Original version
 **/
public interface COMM_IDO_OrderItemSummary {
}