/**
 * @author           Daniel Reto
 * @description      Subscription Domain object interface
 *
 * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer        Date             Description
 * -----------------------------------------------------------------------------------
 * Daniel Reto      09/04/2024       ECOMM-192: Original version
 **/
public interface COMM_IDO_Subscription {
}