/**
 * @author Daniel Reto
 * @description Model for Case details for Subscription form.
 *
 * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer        Date             Description
 * -----------------------------------------------------------------------------------
 * Daniel Reto      21/10/2024       Original version
 **/
@SuppressWarnings('PMD.AvoidGlobalModifier')
global class COMM_WS_FormDetailsOutput {
    global String personalFirstName;
    global String personalLastName;
    global String personalVAT;
    global String personalAddress;
    global String personalCity;
    global String personalCountry;
    global String personalZipCode;
    global String personalPhoneCode;
    global String personalPhoneNumber;
    global String personalEmail;
    global String jobRole;
    global String vehicleBrand;
    global String vehicleModel;
    global String vehicleLicense;
    global String secondVehicleBrand;
    global String secondVehicleModel;
    global String secondVehicleLicense;
    global String recordTypeName;
    global String recordTypeDeveloperName;
    global String airport;
    global String status;
}