/**
 * @author Miguel Freire
 * @description Group Domain object interface
 *
 * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer        Date             Description
 * -----------------------------------------------------------------------------------
 * Miguel Freire    18/04/2024       Original version
 **/
public interface COMM_IDO_Group {
}