/**
 * @author Miguel Freire
 * @description Group SObject Domain object class
 *
 * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer        Date             Description
 * -----------------------------------------------------------------------------------
 * Miguel Freire    18/04/2024       Original version
 **/
public inherited sharing class COMM_DO_Group implements COMM_IDO_Group {
    public final static string GROUP_NAME_PARTNER_ADMIN = 'Partner Admin';
    public final static string QUEUE_NAME_SUBSCRIPTION_SABA = 'COMM_SubscriptionRequestSABA';
}