/**
 * @author           Daniel Lascas
 * @description      Case Domain object interface
 *
 * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer        Date             Description
 * -----------------------------------------------------------------------------------
 * Daniel Lascas    18/03/2024       ECOMM-368: Original version
 **/
public interface COMM_IDO_Case {
}