/**
 * @author Diogo Gonçalves
 * @description COMM_OMS_ReservationEmailBCC__mdt repo interface
 *
 * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer        Date             Description
 * -----------------------------------------------------------------------------------
 * Diogo Gonçalves  09/09/2024       Original version
 **/
public interface COMM_IREP_ReservationEmailBCCMdt {
    /**
     * Get all COMM_OMS_ReservationEmailBCC__mdt records
     * @return List<String>
     */
    List<String> getAllEmails();
}