/**
 * @author Daniel Lascas
 * @description Profile SObject Domain object class
 *
 * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer        Date             Description
 * -----------------------------------------------------------------------------------
 * Daniel Lascas    22/02/2024       Original version
 **/
public inherited sharing class COMM_DO_Profile implements COMM_IDO_Profile {
    public final static string PROFILE_NAME_PARTNER_ADMIN = 'Customer Community Plus Login User';
    public final static string PROFILE_NAME_SUPER_PARTNER_ADMIN = 'Customer Community Plus User';
    public final static string PROFILE_NAME_IDENTITY_USER = 'Customers';
    public final static string PROFILE_NAME_SYS_ADMIN = 'System Administrator';
}