/**
 * @author Diogo Gonçalves
 * @description Create Voucher exception class to get the error message
 * linked to creation of QR Codes for the vouchers
 *
 * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer        Date             Description
 * -----------------------------------------------------------------------------------
 * Diogo Gonçalves  10/05/2024       Original version
 **/
public class COMM_SL_CreateVoucherException extends Exception {
}