/**
 * @author Miguel Freire
 * @description COMM_REP_GroupMember test class
 *
 * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer        Date            Coverage(%)    Description
 * -----------------------------------------------------------------------------------
 * Miguel Freire    18/04/2024      100            Original version
 **/
@isTest
private class COMM_REP_GroupMemberTest {
}