/**
 * @author Miguel Freire
 * @description Group Member repository
 *
 * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer        Date             Description
 * -----------------------------------------------------------------------------------
 * Miguel Freire    18/04/2024       Original version
 **/
public inherited sharing class COMM_REP_GroupMember extends FW_SobjectRep implements COMM_IREP_GroupMember {
}