/**
 * @author Daniel Lascas
 * @description Account SObject Domain object class
 *
 * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer        Date             Description
 * -----------------------------------------------------------------------------------
 * Daniel Lascas    22/02/2024       Original version
 **/
public interface COMM_IDO_Account {
}