/**
 * @author           Daniel Reto
 * @description      Capacity Domain object interface
 *
 * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer        Date             Description
 * -----------------------------------------------------------------------------------
 * Daniel Reto      11/04/2024       ECOMM-204: Original version
 **/
public interface COMM_IDO_Capacity {
}