/**
 * @author Daniel Lascas
 * @description Attachment repository interface
 *
 * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer        Date             Description
 * -----------------------------------------------------------------------------------
 * Daniel Lascas    19/03/2024       ECOMM-368: Original version
 **/
public interface COMM_IREP_Attachment extends FW_ISObjectRep {
}