/**
 * @author Miguel Freire
 * @description Group Member repository interface
 *
 * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer        Date             Description
 * -----------------------------------------------------------------------------------
 * Miguel Freire    18/04/2024       Original version«
 **/
public interface COMM_IREP_GroupMember extends FW_ISObjectRep {
}