/**
 * @author Daniel Lascas
 * @description Product2 Domain object interface
 *
 * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer        Date             Description
 * -----------------------------------------------------------------------------------
 * Daniel Lascas    10/04/2024       ECOMM-194: Original version
 **/
public interface COMM_IDO_Product2 {
}