/**
 * @author           Daniel Lascas
 * @description      COMM_MonthlyFiscalDocumentControl__c Domain object interface
 *
 * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer        Date             Description
 * -----------------------------------------------------------------------------------
 * Daniel Lascas    15/04/2024       ECOMM-194: Original version
 **/
public interface COMM_IDO_MonthlyFiscalDocumentControl {
}