/**
 * @author Daniel Lascas
 * @description User Domain object interface
 *
 * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer        Date             Description
 * -----------------------------------------------------------------------------------
 * Daniel Lascas    21/02/2024       Original version
 **/
public interface COMM_IDO_User {
}