/**
 * @author Daniel Lascas
 * @description PermissionSet Domain object interface
 *
 * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer        Date             Description
 * -----------------------------------------------------------------------------------
 * Daniel Lascas    02/04/2024       ECOMM-700: Original version
 **/
public interface COMM_IDO_PermissionSet {
}