/**
 * @author Daniel Lascas
 * @description COMM_MonthlyFiscalDocumentControl__c repository interface
 *
 * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer        Date             Description
 * -----------------------------------------------------------------------------------
 * Daniel Lascas    15/04/2024       ECOMM-194: Original version
 **/
public interface COMM_IREP_MonthlyFiscalDocumentControl extends FW_ISObjectRep {
}