/**
 * @author           Daniel Lascas
 * @description      COMM_IDO_PortalValidationSetting Custom Metadata Domain object interface
 *
 * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer        Date             Description
 * -----------------------------------------------------------------------------------
 * Daniel Lascas    21/03/2024       US usNumber - Original version
 **/
public interface COMM_IDO_PortalValidationSetting {
}