/**
 * @author Daniel Lascas
 * @description Attachment repository
 *
 * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer        Date             Description
 * -----------------------------------------------------------------------------------
 * Daniel Lascas    19/03/2024       ECOMM-368: Original version
 **/
public inherited sharing class COMM_REP_Attachment extends FW_SobjectRep implements COMM_IREP_Attachment {
}