/**
 * @author Daniel Lascas
 * @description COMM_SubscriptionInvoice__c Domain object interface
 *
 * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer        Date             Description
 * -----------------------------------------------------------------------------------
 * Daniel Lascas    28/03/2024       ECOMM-194: Original version
 **/
public interface COMM_IDO_SubscriptionInvoice {
}