/**
 * @author Daniel Lascas
 * @description Profile Domain object interface
 *
 * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer        Date             Description
 * -----------------------------------------------------------------------------------
 * Daniel Lascas    22/02/2024       Original version
 **/
public interface COMM_IDO_Profile {
}