/**
 * @author Daniel Lascas
 * @description Contact Domain object interface
 *
 * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer        Date             Description
 * -----------------------------------------------------------------------------------
 * Daniel Lascas    04/04/2024       ECOMM-708 - Original version
 **/
public interface COMM_IDO_Contact {
}