/**
 * @author Daniel Reto
 * @description Model for update Form Details.
 *
 * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer        Date             Description
 * -----------------------------------------------------------------------------------
 * Daniel Reto      23/10/2024       Original version
 **/
@SuppressWarnings('PMD.AvoidGlobalModifier')
global class COMM_WS_UpdateFormDetailsOutput {
    global String caseStatus;
}