/**
 * @author           Daniel Reto
 * @description      Order Summary Domain object interface
 *
 * Modification Log
 * ------------------------------------------------------------------------------------
 * Developer        Date             Description
 * -----------------------------------------------------------------------------------
 * Daniel Reto      20/06/2024       Original version
 **/
public interface COMM_IDO_OrderSummary {
}