/**
    * @description   Exception type thrown by the trigger handler or wrapper.
    * @testClass     N/A
    * Modification Log 
	* ------------------------------------------------------------------------------------  
	* Developer                       Date                Description  
    * ------------------------------------------------------------------------------------ 
*/
public class FW_TriggerException extends Exception {}